sudo: false
dist: trusty
language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
jdk:
  - oraclejdk7
cache:
  - ccache
  - apt

addons:
   apt:
      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
      packages: ['clang-3.6' , 'g++-6', 'zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'curl', 'libgflags-dev']
env:
  # Run all tests before db_block_cache_test (db_test, db_test2)
  - JOB_NAME=unittests ROCKSDBTESTS_END=db_block_cache_test
  # Run all tests starting from db_block_cache_test (db_block_cache_test, ..., plain_table_db_test)
  - JOB_NAME=unittests ROCKSDBTESTS_START=db_block_cache_test ROCKSDBTESTS_END=comparator_db_test
  # Run all tests starting from db_block_cache_test (comparator_db_test, ...)
  - JOB_NAME=unittests ROCKSDBTESTS_START=comparator_db_test
  # Run java tests
  - JOB_NAME=java_test
  # Build ROCKSDB_LITE
  - JOB_NAME=lite_build

matrix:
  exclude:
  - os: osx
    compiler: gcc

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == 'linux' && "${CXX}" == 'clang++' ]]; then CXX=clang++-3.6; fi
  # test one linux g++ build with g++-6
  - if [[ "${TRAVIS_OS_NAME}" == 'linux' && "${CXX}" == 'g++' && "${JOB_NAME}" == 'unittests' ]]; then CXX=g++-6; fi
  # Limit the maximum number of open file descriptors to 8192
  - ulimit -n 8192 || true

script:
  - ${CXX} --version
  - if [[ "${JOB_NAME}" == 'unittests' ]]; then OPT=-DTRAVIS V=1 make -j4 check_some; fi
  - if [[ "${JOB_NAME}" == 'java_test' ]]; then OPT=-DTRAVIS V=1 make clean jclean rocksdbjava jtest; fi
  - if [[ "${JOB_NAME}" == 'lite_build' ]]; then OPT="-DTRAVIS -DROCKSDB_LITE" V=1 make -j4 static_lib; fi
notifications:
  slack:
    rooms:
      secure: S9sPiLpGnRXLWqhc5sONu463Bsxeo+jvE2VUEkYGY4cdVylTLlkYXcuVP0XrGbRLiYrL2SBdl4gNO/N04de0yhtAkEJvjzJbeex/NxQot8FN0Q/noJ1wo3iJmGfpeY3HaLXidlR3l15qFpKVYtt4UWRTWdBLlUuEBukyYWam47dF/+AN4roTgSA53A0qXcY8UsO9n8h2YknQF5VFbCMIy4YfaZDaGciFIAJMAjBiKcONmLPq3f9zNeMQcK8tpGMPeDkgiuB024LGvrTHUoZ8RskKv6o8oYP372QLr7AoxwgNg8dvSjQmDw/S/1LHjirDWmz9VqoUqPmaVkEF7C3KKsn5HbDcJpM1AJe6HfYVjTfGL3sBsmFg+8y+e71goMvBOdwQO+ewYKaullxIrrjRZpa3MFwLeFADD0bqX7nOhUtn+utb5D0kLBmeRMXJM19niooPbPFynuN/xcwR1e3xNkmCdtbl9pnBkwlJrfqytRaJfcjC5YBVluVd+PlTCChZ49e6goQ+JUzGxm2/HqfK1So9R76zbEEnGNwD5Qan2wsSNfMtwG7yD9giz8Z6fXiEKuQ5D/vZ61sbGnORDqCeFWgh+s0dg1jxqAXMhz5XQXDQh1FEu7VZC5B/kLdR/Anex31/HtQihs7fztSsMe1xxjM+FffjMBATvumMtfuvOaU=
    on_success: change
    on_failure: always
